### ISSUE TITLE
Lenguaje de programación

### ISSUE THREAD

**Issue by blancagiron** [ChinChainis/Proyecto_Reparahorarios_IV2425#10]
Hola! Para poder trabajar sobre tu repositorio tenemos que ver que lenguaje sería más adecuado para tu proyecto y cuál querías usar, ¿tienes alguna preferencia o alguna sugerencia?

**Comment by ChinChainis** [comment]
Hola! Al principio tenía pensado usar python pero por recomendación del profesor y por tema de mejorar mis métodos de organización de código voy a emplear Go. ¿Cómo lo ves para mi proyecto?

**Comment by blancagiron** [comment]
Pues aunque no conozco mucho Go, por lo que he visto creo que puede ser una buena elección para tu proyecto, ya que parece ser fácil de organizar y contar con funciones útiles para el procesamiento y la extracción de datos :)
